<?php
namespace MrfExpressive;

use Exception;

class MethodNotImplementedException extends \Exception
{
    public function __construct($message = "", $code = 0, Exception $previous = null)
    {
        $message = sprintf('Method %s was not implemented', $message);

        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }

}